version: '3.8'

services:
  flask-backend:
    build:
      context: ./Python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  dotnet-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5161:5161"
    restart: always